In [1]:
import pandas as pd
import numpy as np
import datetime
import time

In [ ]:
1. User will input (3ages).Find the oldest one

In [6]:
list1 = eval(input('Enter 3 ages'))
max(list1)

Enter 3 ages [40,12,76]


76

In [ ]:
2. Write a program that will convert celsius value to fahrenheit

In [7]:
cel = eval(input('enter temp in celcius'))

fahrenhit= (cel*9/5)+32
fahrenhit

enter temp in celcius 30


86.0

In [ ]:
3. User will input (2numbers).Write a program to swap the numbers

In [8]:
list1 = [1,2,4,5,6,8,3,7,9]

list1[2] ,list1[4] = list1[4],list1[2]

list1

[1, 2, 6, 5, 4, 8, 3, 7, 9]

In [ ]:
4. Write a program that will give you the sum of 3 digits

In [10]:
x= 12; y= 11; z = 4           #cannot do sum() for more than 2 nums

summ = x+y+z
summ

27

In [ ]:
5. Write a program that will reverse a four digit number.Also it checks whether the reverse is true.

In [16]:
x = '1234'
x[::-1]

'4321'

In [17]:
x==x[::-1]

False

In [ ]:
6. Write a program that will tell whether the number entered by the user is odd or even.

In [18]:
x = eval(input('enter a num'))

if x%2==0:
    print('num is even')
else:
    print('num is odd')

enter a num 4


num is even


In [ ]:
7. Write a program that will tell whether the given year is a leap year or not.

In [19]:
year = eval(input('enter a year'))

if year%4==0:
    print('leap year')
else:
     print('not leap year')
    

enter a year 1994


not leap year


In [ ]:
8. Write a program to find the euclidean distance between two coordinates

In [ ]:
9. Write a program that take a user inputr of three angles and will find out whether it can form a triangle or not

In [22]:
x= eval(input('enter an angle'))
y= eval(input('enter an angle'))
z= eval(input('enter an angle'))

if x+y+z==180:
    print('angles of triangle')
else:
    print('angles not of triangle')

enter an angle 12
enter an angle 34
enter an angle 23


angles not of triangle


In [ ]:
10. Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit

In [23]:
cost = eval(input('enter a price'))
selling = eval(input('enter a price'))

if selling-cost>0:
    print('profit')

else:
    print('loss')

enter a price 120
enter a price 150


profit


In [ ]:
11. Write a program to find the simple interest when the value of principle,rate of interest and time period is given.

In [26]:
p= eval(input('enter amount'))
r=eval(input('enter amount'))
t=eval(input('enter amount'))

simple = (p*r*t)/100
simple

enter amount 12000
enter amount 7
enter amount 10


8400.0

In [ ]:
12. Write a program to find the volume of the cylinder. Also find the cost when ,when the cost of 1litre milk is 40Rs.

In [35]:
r= float(input('r'))
h= float(input('h'))
vol1 = (22/7)*r*h
vol= np.sqrt(vol1)
print(vol)
rs= vol*40.0
rs

r 4
h 8


10.028530728448139


401.14122913792556

In [ ]:
13. Write  a program that will tell whether the given number is divisible by 3 & 6.

In [37]:
x = int(input('num'))

if x%3==0 and x%6==0:
    print('given number is divisible by 3 & 6')

else:
    print('given number not is divisible by 3 & 6')

num 34


given number not is divisible by 3 & 6


In [ ]:
17. Write a program that will take three digits from the user and add the square of each digit

In [39]:
x=3
y=2
z=6

kl =lambda x,y,z: x**2+y**2+z**2
kl(x,y,z)

49

In [ ]:
18. Write a program that will check whether the number is armstrong number or not.

In [48]:
num = str(input('num'))

dig = int(num)
sum_num=0
def arm(num):
    global sum_num
    for d in num:
        sum_num+= int(d)**3
    return sum_num

arm(num)
print(sum_num)
if sum_num == dig:
    print('arm num')
else:
    print('not arm')

num 371


371
arm num


In [ ]:
22. Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

In [ ]:
dhead= 20
clegs= 80



In [ ]:
24. Write a program to find the sum of first n numbers, where n will be provided by the user. Eg if the user provides n=10 the output should be 55.

In [51]:
list1 = [1,6,4,0,8,6,4,9,1,2]

summ =0
n= 5
for i in range(n):
    summ+=list1[i]
    print(summ)

1
7
11
11
19


In [ ]:
25. Write a program that can multiply 2 numbers provided by the user without using the * operator

In [53]:
x=2; y= 5
np.dot(x,y)

10

In [ ]:
26. Write a program that can find the factorial of a given number provided by the user

In [57]:
n =5
fact=1
for i in range(1, n+1):
    fact*=i
    print(fact)

1
2
6
24
120


In [ ]:
27. Write a program to print the first 25 odd numbers

In [59]:
list1=[]

for i in range(1,50):
    if i%2==1:
        list1.append(i)

print(list1[:25])
print(len(list1[:25]))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
25


In [ ]:
28. Write a program to print whether a given number is prime number or not

In [60]:
n= 7

for i in range(2,n):
    if n%i==0:
        print('num is not prime')
    else:
        print('num is prime')

num is prime
num is prime
num is prime
num is prime
num is prime


In [ ]:
29. Print all the armstrong numbers in the range of 100 to 1000

In [61]:
for i in range(100,1000):
    num = str(i)
    tot_sum = int(num[0])**3+int(num[1])**3+int(num[2])**3
    if i==tot_sum:
        print(i)
    else:
        pass

153
370
371
407


In [ ]:
30. The current population of a town is 10000. The population of the town is increasing at the rate of 10% per year. 
You have to write a program to find out the population at the end of each of the last 10 years. 
For eg current population is 10000 so the output should be like this:

In [64]:
year = 10; pop= 10000

for i in range(1,10):
    year=10- i
    pop= pop-0.1*pop
    print(year,pop)

9 9000.0
8 8100.0
7 7290.0
6 6561.0
5 5904.9
4 5314.41
3 4782.969
2 4304.6721
1 3874.20489


In [ ]:
31. Write a program to print all the unique combinations of 1,2,3 and 4

In [ ]:
32. User will provide 2 numbers you have to find the HCF of those 2 numbers

In [70]:
one = 20
sec = 25

one_fac=[]
sec_fac=[]
for i in range(1,one):
    if one%i==0:
        one_fac.append(i)
for j in range(1,one):
    if sec%j==0:
        sec_fac.append(j)

print(one_fac,sec_fac)

commom= []

for q in one_fac:
    if q in sec_fac:
        commom.append(q)
print(max(commom))

[1, 2, 4, 5, 10] [1, 5]
5


In [ ]:
33. User will provide 2 numbers you have to find the by LCM of those 2 numbers

In [71]:
one = 20
sec = 25

one_fac=[]
sec_fac=[]
for i in range(1,one):
    if one%i==0:
        one_fac.append(i)
for j in range(1,one):
    if sec%j==0:
        sec_fac.append(j)

print(one_fac,sec_fac)

commom= []

for q in one_fac:
    if q in sec_fac:
        commom.append(q)
print(min(commom))

[1, 2, 4, 5, 10] [1, 5]
1


In [ ]:
34. Print first 25 prime numbers

In [ ]:
37. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.

In [77]:
new= int(input('num'))
n= str(new)
nn= n*2
nnn= n*3

req = int(n)+int(nn)+int(nnn)
req

num 2


246

In [ ]:
38. Take a number from the user and find the number of digits in it. 

In [79]:
nm = 1234
new = str(nm)
len(new)

4

In [ ]:
39.Print all factors of a given number provided by the user.

In [80]:
n = 12
for i in range(1, n):
    if n%i ==0:
        print(i)

1
2
3
4
6


In [ ]:
40. Find the reverse of a number provided by the user(any number of digit) 

In [83]:
dig = 1234
st_dig = str(dig)

print(int(st_dig[::-1]))

4321


In [ ]:
41. Write a program to print the following pattern

In [84]:
for i in range (1, 6):
    print('*'*i)

*
**
***
****
*****


In [ ]:
42. Write a program to print the following pattern

In [87]:
for i in range (1, 3):
    print('*'*i)
for i in range (3, 0,-1):
    print('*'*i)

*
**
***
**
*


In [ ]:
43. Write  a program to print the following pattern

In [91]:
for i in range(1,5):
    for j in range(i):
        print('*'*j,'\r')

 
 
* 
 
* 
** 
 
* 
** 
*** 


In [ ]:
45. Write a program to print the following pattern

In [ ]:
49.  Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers.

In [98]:
n=eval(input('enter num'))

num=[]

for j in n:
    if j ==0:
        break
        
    else:
        num.append(j)
        summ = sum(num)
        av= summ/len(num)
print(num, summ, av)

enter num [1,4,6,0,2,3]


[1, 4, 6] 11 3.6666666666666665


In [ ]:
51. Find the length of a given string without using the len() function

In [106]:
stt ='havemore'
coun=0
for i in stt:
    coun+=1
print(coun)

8


In [ ]:
52. Extract username from a given email. 
Eg if the email is nitish24singh@gmail.com then the username should be nitish24singh

In [109]:
import re
x= 'nitish24singh@gmail.com'
re.findall('[a-z0-9]{7,13}',x)

['nitish24singh']

In [ ]:
53. Count the frequency of a particular character in a provided string. Eg 'hello how are you' is the string, the frequency of h in this string is 2.

In [110]:
x= 'hello how are you'

x.count('h')

2

In [ ]:
54. Find the index position of a particular character in another string.

In [112]:
char = 'a'

x = 'my name is given'

x.index(char)

4

In [ ]:
55. Count the number of vowels in a string provided by the user

In [116]:
x = 'given is the strong us'
countt=0
for z in x:
    if z in 'aeiouAEIOU':
        countt+=1
print(countt)

6


In [ ]:
56. Write a program which can remove a particular character from a string

In [117]:
stt= 'I am strong'

stt.replace('a','')

'I m strong'

In [ ]:
57. Write a program that can check whether a given string is palindrome or not.

In [118]:
stt = 'appa'
stt==stt[::-1]

True

In [119]:
stt = 'papa'
stt==stt[::-1]

False

In [ ]:
58. Write a python program to remove all the duplicates from a list

In [120]:
list1= [1,3,2,1,4,1,2,6,7,8]
s = set(list1)

new_list = list(s)
new_list

[1, 2, 3, 4, 6, 7, 8]

In [ ]:
59. Write a python program to convert a string to title case without using the title()

In [124]:
stt = 'my name is smruti pote'

tit=[]
s_list = stt.split()
for i in s_list:
    new = i[0].upper()+i[1:]
    tit.append(new)
print(' '.join(tit))

My Name Is Smruti Pote


In [ ]:
60. Write a python program to find the max item from a list without using the max function

In [130]:
listt = [4,1,5,9,2,7,3]

In [132]:
listt.sort()

In [134]:
listt[-1]

9

In [ ]:
61. Write a python program to reverse a list

In [135]:
listt = [4,1,5,9,2,7,3]
listt[::-1]

[3, 7, 2, 9, 5, 1, 4]

In [141]:
listt =[2,5,3,8,1]

listt.index(3)

2

In [ ]:
63. Write a program that can create a new list from a given list where each item in the new list is square of the item of the old list

In [145]:
listt =[2,5,3,8,1]
new=[x**2 for x in listt]
new

[4, 25, 9, 64, 1]

In [ ]:
64. Write a program that can reverse words of a given string.
Eg if the input is Hello how are you
Output should be you are how Hello

In [149]:
stt = 'Hello how are you'

s = stt.split()
s[::-1]
print(' '.join(s[::-1]))

you are how Hello


In [ ]:
65. Write a program that can count the number of words in a given string

In [153]:
stt = 'my name anthony gonsalvis excuse me please'
s= stt.split()

co=0
for i in s :
    co+=1
print(co)
    

7


In [ ]:
66. Write a program to check if a list is in ascending order or not

In [160]:
import copy

In [158]:
lis1 = [2,4,5,6,7,7]

In [156]:
lis1 == lis1.sort()

False

In [165]:
lis1 = [1,2,3,4,5,6]

In [166]:
lis2= copy.deepcopy(lis1)

In [167]:
lis2

[1, 2, 3, 4, 5, 6]

In [168]:
lis2.sort()

In [170]:
lis2==lis1

True

In [ ]:
67. Create 2 lists from a given list where 1st list will contain all the odd numbers from the original list and 
the 2nd one will contain all the even numbers 

In [173]:
lis1 = [1,2,3,4,5,6,7,8,9]
eve =[x for x in lis1 if x%2==0]
od = [x for x in lis1 if x%2==1]
print(eve,od)

[2, 4, 6, 8] [1, 3, 5, 7, 9]


In [ ]:
68. Write a program to merge 2 list without using the + operator

In [179]:
lis1 =[1,2,3]
lis2 =[5,6,7]
lis1.extend(lis2)

In [180]:
lis1

[1, 2, 3, 5, 6, 7]

In [ ]:
69. Write a program to replace an item with a different item if found in the list

In [188]:
lis1 = [1,2,34,5,6]

In [ ]:
70. Write a program that can convert a 2D list to 1D listWrite a program that can print 

In [191]:
lis = [[1,2],[2,3]]
np.ravel(lis)

array([1, 2, 2, 3])

In [ ]:
71. Write a program that can perform union and intersection on 2 given list.

In [196]:
lis1 =[1,2,3]
lis2 =[5,6,7,3]

s1=set(lis1)
s2=set(lis2)

uni = s1.union(s2)
inter = s1.intersection(s2)

print(list(uni), list(inter))

[1, 2, 3, 5, 6, 7] [3]


In [ ]:
72. the max item of each row of a matrix. 

In [197]:
arr = np.random.randint(1,25,size = (4,4))
arr

array([[18,  2,  2, 14],
       [15, 19,  3, 13],
       [17,  6, 23, 22],
       [18, 23,  7, 16]])

In [201]:
for i in range(arr.shape[0]):
    print(arr[i].max())

18
19
23
23


In [ ]:
73. Write a program that can convert an integer to string

In [202]:
val = 1223
s= str(val)
s

'1223'

In [ ]:
74. Write a program to print the shape of a matrix. 

In [203]:
arr.shape

(4, 4)

In [ ]:
75. Write a program that can check if you can perform matrix multiplication on 2 matrices

In [204]:
arr1 = np.random.randint(1,25,size = (4,4))
arr2= np.random.randint(1,25,size = (4,4))
print(arr1)
print(arr2)

[[11 23 24 23]
 [20  4  7 23]
 [18  6 24  4]
 [ 6  1 10 13]]
[[23  8 12 18]
 [ 8 14  3 22]
 [ 1  2 12 10]
 [24 12 19 11]]


In [205]:
arr1*arr2

array([[253, 184, 288, 414],
       [160,  56,  21, 506],
       [ 18,  12, 288,  40],
       [144,  12, 190, 143]])

In [206]:
lis1 = [1,2,3,4,5,6,6,7]

In [207]:
lis1.count(6)

2

In [ ]:
79. Assume a list with numbers from 1 to 10 and then convert it into a dictionary where the key would be the 
numbers of the list and the values would be the square of those numbers.


In [208]:
list1 = [1,2,3,4,5,6,7,8]
list2 = [x**2 for x in list1]

In [209]:
dict(zip(list1,list2))

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [ ]:
80. Write a program to merge two given dictionary


In [210]:
d1= {1: 1, 2: 4, 3: 9, 4: 16}
d2 ={5: 25, 6: 36, 7: 49, 8: 64}

In [218]:
d1.update(d2)

In [219]:
d1

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

In [220]:
list1=[(9,2),(4,6),(1,2),(7,4),(5,7)]
list1.sort()

In [221]:
list1

[(1, 2), (4, 6), (5, 7), (7, 4), (9, 2)]

In [224]:
list3=[1,2,3,4,5]

sqr = lambda listt : [x**2 for x in listt]
cub = lambda listt : [x**3 for x in listt]

sqr(list3)
cub(list3)

[1, 8, 27, 64, 125]

In [225]:
string='elephants are huge'
check  = lambda stt : stt[0]=='e'
check(string)

True

In [226]:
string='string'
dig = lambda stt : stt.isdigit()
dig(string)

False

In [229]:
list1=[1,2,3,4,5]
list2=[4,5,6,7,8]

list(filter(lambda x: x in list1,list2))

[4, 5]

In [230]:
lst1=[5,2,3,6,8,7,1,9]
eve = lambda lst :  [x%2==0 for x in lst]
odd = lambda lst :  [x%2!=0 for x in lst]
eve(lst1)
odd(lst1)

[True, False, True, False, False, True, True, True]

In [231]:
lst1=[5,2,3,6,8,7,1,9]
list(filter(lambda x : x%2==0,lst1))

[2, 6, 8]

In [234]:
list1=[1,2,3,4]
list2=[2,3,4,1]

list(map(lambda x,y: x+y,list1,list2))

[3, 5, 7, 5]

In [236]:
list2=[26,39,22,76,90,38]
list(filter(lambda x : x%9==0 or x%13==0,list2))

[26, 39, 90]

In [240]:
string1 = ['cat', 'play', 'act', 'god', 'dog', 'help']

result = list(filter(lambda x: ''.join(sorted(x)) == x, string1))
print(result)


['act']


In [243]:
tup=('1234')
l = list(tup)

ss = ''.join(l)
ss

'1234'

In [249]:
list1=[1,2,3,4]

list2=[2,4,7,8]

list(filter(lambda x: x not in list2,list1))

[1, 3]

In [301]:
n=5
for i in range(1,n+1):
    print(' '*(n-i),end ='')
    print(' *'*i)

     *
    * *
   * * *
  * * * *
 * * * * *


In [294]:
n=5
x =64
for i in range(1, n+1):
    for j in range(i):
        print(chr(x+i),end =' ')
    print(' ')

A  
B B  
C C C  
D D D D  
E E E E E  


In [298]:
n=  5
for i in range(1,n+1):
    for j in range(i):
        print(i,end ='')
    print()

1
22
333
4444
55555


In [312]:
n=5
for i in range(1,n+1):
    for j in range(i):
        print('*'*j,end ='')
    print( )


*
***
******
**********


In [314]:
list3=[1,2,3,4,5]
list(map(lambda x : x**3,list3))

[1, 8, 27, 64, 125]

In [316]:
lst1=[5,2,3,6,8,7,1,9]

len(list(filter(lambda x : x%2!=0,lst1)))

5

In [317]:
list3=['madam','apple','lady','abba']
list(filter(lambda x: x==x[::-1],list3))

['madam', 'abba']

In [319]:
list1=['python','maths','python','chem','maths','maths']
count=list(map(lambda x : list1.count(x),list1))

dict(zip(list1,count))

{'python': 2, 'maths': 3, 'chem': 1}

In [320]:
list1=['my','name','is','smruti']

list(map(lambda x: x.split(),list1))

[['my'], ['name'], ['is'], ['smruti']]

In [321]:
dict1={'name':'Smruti','last_name':'Pote','Age':29,"place":'Pune'}

for i,

['Age', 'last_name', 'name', 'place']

In [322]:
dict1={'name':'Smruti','last_name':'Pote','Age':29,"place":'Pune'}

sorr= {}
for keys in sorted(dict1.keys()):
    sorr[keys]=dict1[keys]

print(sorr)

{'Age': 29, 'last_name': 'Pote', 'name': 'Smruti', 'place': 'Pune'}


In [327]:
dict1={'phy':75,'chem':40,'maths':50,"history":49}
sorr={}
for i in sorted(dict1.values()):
    for j in dict1:
        if dict1[j]==i:
            sorr[j]=dict1[j]
print(sorr)

{'chem': 40, 'history': 49, 'maths': 50, 'phy': 75}


In [331]:
dict2={'age':25,'weight':85,'Height':7.5,'waist':36}

x= dict2.values()
sum(x)

153.5

In [ ]:
dict1={'phy':75,'chem':40,'maths':50,"history":49}


In [339]:
lst=['cat','dog','pam','act','god','map']

ll=[]
for i in range(0,len(lst)):
    for j in range(i+1,len(lst)):
        if lst[i] == sorted(lst[j]):
            ll.append(lst[i])
            ll.append(lst[j])

ann=[]
for k in range(0,len(ll),2):
    ll = ll[k],ll[k+1]
    ann.append(ll)

print(ann)

[]


In [343]:
string='I am good at python language and python language is easy to write and understand'
list1= string.split()
list2 = list(map(lambda x: list1.count(x),list1))
list2

dict(zip(list1,list2))

{'I': 1,
 'am': 1,
 'good': 1,
 'at': 1,
 'python': 2,
 'language': 2,
 'and': 2,
 'is': 1,
 'easy': 1,
 'to': 1,
 'write': 1,
 'understand': 1}

In [345]:
lst=[(1,2),(3,7),(9,6),(7,5)]

result= (lambda lst: sorted(lst,key = lambda x: x[1]))
result(lst)

[(1, 2), (7, 5), (9, 6), (3, 7)]

In [2]:
from abc import ABC,abstractmethod

In [6]:
class ModelAbs(ABC):
    @abstractmethod
    def first(self):
        print('first class')
    @abstractmethod    
    def login(self):
        print('self')

class Register():
    def first(self):
        print('first class')
    # def login(self):
    #     print('self')

obj = Register()
obj.login()

AttributeError: 'Register' object has no attribute 'login'

In [10]:
class ModelAbs():
    max = 2

    def __init__(self,a):
        self.a =a
    
    def first(self):
        summ = self.a+self.max
        
        print(f'summ',summ)
   

class Register(ModelAbs):
    def __init__(self,a,b):
        ModelAbs.__init__(self,a)
        self.b =a
        
    def name(self):
        names = self.b+self.max
        print(f'name', names)

obj = Register(4,3)
obj.name()

name 6
